services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_static_site
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro